server:
  port: 8083
spring:
  datasource:
    username: postgres
    password: VeryStronGPassWord@1137
    url: jdbc:postgresql://13.49.226.163:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
okta:
  oauth2:
    audience: https://travel-management-system.eu.auth0.com/api/v2/
    issuer: https://travel-management-system.eu.auth0.com/

