server:
  port: 8083
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/bustravelapp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

